apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
  - blue-green.yaml
patchesStrategicMerge:
  - blue-green-patch.yaml
namespace: default
images:
  - name: your-repo/app
    newTag: v2