apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-rolling
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # 33% unavailable max
      maxSurge: 1        # 33% surge
  selector:
    matchLabels:
      app: rolling
  template:
    metadata:
      labels:
        app: rolling
    spec:
      containers:
        - name: app
          image: your-repo/app:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-rolling-svc
spec:
  selector:
    app: rolling
  ports:
    - port: 80
      targetPort: 8080