apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'app'
        metrics_path: /metrics
        static_configs:
          - targets:
              - app-big-bang-svc:8080
              - app-rolling-svc:8080
              - app-canary-svc:8080
              - app-bluegreen-svc:8080
            labels:
              app: deployment-strategies