apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strategies-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ines312692/deployment-strategies-repo.git
    targetRevision: HEAD
    path: k8s/strategies
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true