apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
  - ../../strategies/big-bang.yaml
patchesStrategicMerge:
  - big-bang-patch.yaml
namespace: default
images:
  - name: your-repo/app
    newTag: v1